sidebar:
    - id: "main-sidebar"
      path: "pt-br/"
      style: "docked"
      contents:
        - href: pt-br/index.qmd
          text: "Início"
        - section: "Módulos"
          contents:
            - text: "Semana 01: Fundamentos de Desenvolvimento Bare-Metal"
              href: pt-br/semana-01/teoria.qmd